name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Log
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.GH_TOKEN }}
          echo "ENV:  "
          echo $GH_TOKEN
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.GH_TOKEN}} | sed 's/./& /g'
      - run: yarn install
      - run: yarn lint
      - run: yarn check-format
      - run: yarn check-types
      - run: yarn test:ci
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn semantic-release
